const CHARACTERS=[
 {id:'baekhogu',name:'백호구',en:'Baekhogu',emotion:'허세',bg:'#EEF4FF',pos:'-346px -247px',lead:'자신감 넘치는 허세 캐릭터. 큰소리치지만 정 많고 사랑스러운 분위기 메이커.',personality:'자신감과 허세가 공존하는 리더형. 위기에도 먼저 나서며 친구들에게 활력을 불어넣는 존재.',speech:['이 정도는 내가 가볍게 해내지!','다들 나만 믿고 따라와!'],service:'SOOP 라이브 방송 리액션 이모티콘\n채팅창 텐션 부스터\n응원 효과음 캐릭터',memes:['#허세폭발','#자신감MAX','#호구리더'],cmyk:[['파란색',100,60,0,0],['볼터치',0,30,18,0]]},
 {id:'gogo',name:'고고',en:'GoGo',emotion:'텐션',bg:'#EEFAFF',pos:'-482px -247px',lead:'항상 에너지 넘치는 텐션 캐릭터. 방송의 흥을 올려주는 존재.',personality:'항상 에너지 넘치고 텐션이 MAX인 캐릭터. 방송을 살아있게 만드는 흥의 아이콘.',speech:['야, 이거 완전 미쳤다!!','텐션 올려~~!! 같이 달리자!!'],service:'SOOP 라이브 방송 리액션 이모티콘\n채팅창 텐션 부스터\n응원 효과음 캐릭터',memes:['#텐션폭발','#에너지드링크_인격화','#방송흥신호','#고고레츠고'],cmyk:[['하늘색',57,5,0,0]]},
 {id:'saida',name:'사이다',en:'Saida',emotion:'팩폭',bg:'#F5F5F5',pos:'-617px -247px',lead:'답답한 순간을 시원하게 정리하는 팩트 폭격수.',personality:'핵심을 찌르는 한마디로 분위기를 정리하는 솔직하고 통쾌한 캐릭터.',speech:['그건 아니지. 팩트만 보자.','답답해서 내가 말한다!'],service:'댓글과 채팅의 사이다 한마디\n상황 정리 리액션 캐릭터',memes:['#팩폭','#사이다발언','#속시원'],cmyk:[['분홍색',0,30,18,0]]},
 {id:'deoldol',name:'덜덜이',en:'Deoldol',emotion:'긴장',bg:'#FFEEEE',pos:'-752px -247px',lead:'늘 긴장하지만 용기를 내어 한 걸음씩 나아가는 캐릭터.',personality:'작은 일에도 온몸으로 긴장하지만 친구들을 위해서는 용기를 내는 반전 매력의 소유자.',speech:['잠깐만… 이거 괜찮은 거 맞지?','떨리지만 한번 해볼게!'],service:'긴장·놀람 리액션\n공감형 채팅 이모티콘',memes:['#덜덜','#긴장MAX','#용기한스푼'],cmyk:[['빨간색',0,84,67,0],['노란색',0,11,91,0],['초록색',46,0,91,0]]},
 {id:'narak',name:'나락이',en:'Narak',emotion:'불안',bg:'#FFF5EE',pos:'-887px -247px',lead:'걱정은 많지만 누구보다 친구를 세심하게 챙기는 캐릭터.',personality:'항상 최악의 상황을 먼저 떠올리지만 덕분에 위험을 빠르게 알아채는 섬세한 친구.',speech:['우리… 나락 가는 거 아니지?','일단 플랜 B부터 만들자.'],service:'불안·당황 리액션\n위기 감지 캐릭터',memes:['#나락주의','#걱정인형','#플랜B'],cmyk:[['다홍색',0,72,40,0]]},
 {id:'kuljam',name:'꿀잼',en:'Kuljam',emotion:'도파민',bg:'#FFF9E2',pos:'-1022px -247px',lead:'재미있는 순간을 절대 놓치지 않는 도파민 수집가.',personality:'언제나 웃음과 재미를 찾아다니며 평범한 순간도 콘텐츠로 바꾸는 재주가 있다.',speech:['이거 완전 꿀잼 각인데?','한 번만 더!'],service:'웃음·재미 리액션\n콘텐츠 하이라이트 캐릭터',memes:['#꿀잼보장','#도파민','#한번더'],cmyk:[['노란색',0,12,90,0],['빨간색',0,88,80,0]]},
 {id:'yeongja',name:'영자',en:'Yeongja',emotion:'묵묵함',bg:'#EEF6FF',pos:'-1157px -247px',lead:'말보다 행동으로 보여주는 수퍼스타즈의 든든한 중심.',personality:'조용하지만 늘 곁을 지키며 결정적인 순간에 팀을 이끄는 믿음직한 캐릭터.',speech:['…좋아. 시작하자.','내가 옆에 있을게.'],service:'묵묵한 응원 리액션\n브랜드 심볼 캐릭터',memes:['#묵묵함','#든든한영자','#중심'],cmyk:[['파란색',80,30,0,0]]}
];
const ENGLISH_NAMES={baekhogu:'BECKHOGU',gogo:'GOGO',saida:'CYDAR',deoldol:'DEOLDEOL',narak:'NARAKI',kuljam:'COOLZAM',yeongja:'YOUNGJA'};
CHARACTERS.forEach(character=>{character.en=ENGLISH_NAMES[character.id]});
const grid=document.querySelector('#characterGrid');let selected=1;
const CARD_STROKES={baekhogu:'#2E81F8',gogo:'#00ADF5',saida:'#797979',deoldol:'#FA7676',narak:'#FF9564',kuljam:'#F39D13',yeongja:'#5B99FF'};
const badgeElement=document.querySelector('#charBadge');
new MutationObserver(()=>{const character=CHARACTERS.find(item=>item.emotion===badgeElement.textContent);if(character)badgeElement.style.backgroundColor=CARD_STROKES[character.id]}).observe(badgeElement,{childList:true});
function cmykRgb(c,m,y,k){return `rgb(${Math.round(255*(1-c/100)*(1-k/100))},${Math.round(255*(1-m/100)*(1-k/100))},${Math.round(255*(1-y/100)*(1-k/100))})`}
function imagePath(c){return `2D_${c.name}.png`}
function downloadAssets(c){
 const threeD=c.id==='saida'?'3D_사이다.zip':c.id==='narak'?'3D_나락이.zip':`3D_${c.name}.png`;
 return [
  {label:'2D SVG (표정)',file:`2D_${c.name}_표정.svg`},
  c.id==='yeongja'?null:{label:'2D SVG (동작)',file:`2D_${c.name}_동작.svg`},
  {label:'2D PNG',file:`2D_${c.name}.png`},
  {label:'3D PNG',file:threeD}
 ].filter(Boolean)
}
function renderCards(){grid.innerHTML=CHARACTERS.map((c,i)=>`<button class="char-card ${i===selected?'active':''}" data-index="${i}" style="background:${c.bg};--stroke:${CARD_STROKES[c.id]}" aria-label="${c.name} 보기"><div class="char-card-img-area"><img src="${imagePath(c)}" alt="${c.name}"></div><div class="char-card-info"><p class="char-card-name">${c.name}</p><p class="char-card-emotion">${c.emotion}</p></div></button>`).join('');grid.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=+b.dataset.index;renderCards();renderPanel()})}
function renderPanel(){const c=CHARACTERS[selected];document.querySelector('#characterVisual').style.background=c.bg;const detail=document.querySelector('#detailImage');detail.src=imagePath(c);detail.alt=c.name;document.querySelector('#charName').textContent=c.name;document.querySelector('#charEnglish').textContent=c.en;document.querySelector('#charBadge').textContent=c.emotion;document.querySelector('#charLead').textContent=c.lead;document.querySelector('#infoGrid').innerHTML=`<div class="info-card"><strong>✦ 성격 설명</strong>${c.personality}</div><div class="info-card"><strong>💬 말투 예시</strong>${c.speech.join('<br>')}</div><div class="info-card"><strong>🔗 서비스 연결</strong>${c.service.replaceAll('\n','<br>')}</div><div class="info-card"><strong>🔥 밈 키워드</strong><div class="chips">${c.memes.map(x=>`<span>${x}</span>`).join('')}</div></div>`;document.querySelector('#assetButtons').innerHTML=downloadAssets(c).map(a=>`<a class="asset-btn" href="${a.file}" download="${a.file}">${a.label}</a>`).join('');document.querySelector('#cmykGrid').innerHTML=c.cmyk.map(x=>`<div class="cmyk-card"><div class="swatch" style="background:${cmykRgb(x[1],x[2],x[3],x[4])}"></div><div class="cmyk-copy"><strong>${x[0]}</strong><small>CMYK&nbsp; ${x.slice(1).join(' · ')}</small></div></div>`).join('')}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.tab;document.querySelectorAll('.tab-panel,.nav-btn').forEach(x=>x.classList.remove('active'));document.querySelector(`#${id}`).classList.add('active');document.querySelector(`.nav-btn[data-tab="${id}"]`).classList.add('active');scrollTo({top:0,behavior:'smooth'})}));document.querySelectorAll('.guide-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.guide-tab,.guide-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(b.dataset.guide==='character'?'#characterGuide':'#printGuide').classList.add('active')});document.querySelectorAll('.policy-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.policy-tab,.policy-pane').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.policy-tab').forEach(x=>x.setAttribute('aria-selected','false'));b.classList.add('active');b.setAttribute('aria-selected','true');document.querySelector(b.dataset.policy==='copyright'?'#copyrightPolicy':'#derivativePolicy').classList.add('active')});renderCards();renderPanel();
